youtube:
  apiKey: ${YOUTUBE_API_KEY}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/social_monitor
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true

server:
  port: 9090

instagram:
  accessToken: ${INSTAGRAM_ACCESS_TOKEN}
  businessAccountId: ${INSTAGRAM_BUSINESS_ID}

twitter:
  apiKey: ${TWITTER_API_KEY}
  host: ${TWITTER_HOST}

huggingface:
  apiKey: ${HUGGINGFACE_API_KEY}