youtube:
  apiKey: AIzaSyAdeO-0srS9kq8YtKEtt7XbKgj3UvJPZho

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/social_monitor
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 9090

instagram:
  accessToken: EAAUuz6nRENIBRJSeCM2UCXYD2doJOyuPRdk5YeSZAZCHrriRZBJtyR0tTesPC9GqaTJASTi7PqnE2QsUSmVpFwODnY1fGDgyrZBQQojCKL4ZCP3iT9oqOMf3P7bG04YzwZAliZAGTyvXnXr8UbnSUuVNRFjNfZAEkgvpoizKZAyDcIce9DUuFvCIvj6AS71XohkZCm
  businessAccountId: "17841443190536872"

twitter:
  apiKey: deb242b238msh26a8efc5c285899p12dfa5jsnac8a1f7cf649
  host: twitter241.p.rapidapi.com

huggingface:
  apiKey: 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
